name:                souffle-haskell
synopsis:            Souffle Datalog bindings for Haskell
description:         Souffle Datalog bindings for Haskell.
version:             0.2.3
homepage:            https://github.com/luc-tielen/souffle-haskell#README.md
license:             MIT
author:              Luc Tielen
maintainer:          luc.tielen@gmail.com
copyright:           2020 Luc Tielen
category:            Logic Programming, Foreign Binding, Bindings
github:              luc-tielen/souffle-haskell
extra-source-files:
  - README.md
  - CHANGELOG.md
  - LICENSE
  - cbits/**/*.h
  - cbits/souffle/LICENSE

dependencies:
  - base >= 4.12 && < 5
  - mtl >= 2.0 && < 3
  - template-haskell >= 2 && < 3
  - type-errors-pretty >= 0.0.1.0 && < 1
  - text >= 1.0 && < 2
  - vector <= 1.0
  - deepseq >= 1.4.4 && < 2
  - directory >= 1.3.3 && < 2
  - filepath  >= 1.4.2 && < 2
  - temporary >= 1.3 && < 2
  - process >= 1.6 && < 2

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -Weverything
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-implicit-prelude
  - -Wno-missed-specializations
  - -Wno-all-missed-specializations
  - -Wno-missing-import-lists
  - -Wno-type-defaults
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-missing-deriving-strategies
  - -optP-Wno-nonportable-include-path
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

cxx-options:
  - -std=c++17

include-dirs:
  - cbits
  - cbits/souffle

install-includes:
  - souffle/FunctorOps.h
  - souffle/AstGroundAnalysis.h
  - souffle/AstTranslator.h
  - souffle/ReadStreamCSV.h
  - souffle/InterpreterIndex.h
  - souffle/RamIndexAnalysis.h
  - souffle/RamVisitor.h
  - souffle/InterpreterEngine.h
  - souffle/SrcLocation.h
  - souffle/RamCondition.h
  - souffle/AstIO.h
  - souffle/Brie.h
  - souffle/AstType.h
  - souffle/swig/SwigInterface.h
  - souffle/ExplainProvenanceImpl.h
  - souffle/AstVisitor.h
  - souffle/Explain.h
  - souffle/AstClause.h
  - souffle/AstIOTypeAnalysis.h
  - souffle/EventProcessor.h
  - souffle/AstAbstract.h
  - souffle/AstProfileUse.h
  - souffle/WriteStreamSQLite.h
  - souffle/DebugReporter.h
  - souffle/AstTransforms.h
  - souffle/InterpreterPreamble.h
  - souffle/AstLiteral.h
  - souffle/MagicSet.h
  - souffle/AstComponent.h
  - souffle/Global.h
  - souffle/AstParserUtils.h
  - souffle/Constraints.h
  - souffle/RamStatement.h
  - souffle/AstNode.h
  - souffle/AstQualifiedName.h
  - souffle/ExplainTree.h
  - souffle/RamTranslationUnit.h
  - souffle/ComponentLookupAnalysis.h
  - souffle/AstArgument.h
  - souffle/RamAnalysis.h
  - souffle/AstAttribute.h
  - souffle/tests/test.h
  - souffle/RamLevelAnalysis.h
  - souffle/LambdaBTree.h
  - souffle/RecordTable.h
  - souffle/SynthesiserRelation.h
  - souffle/AstPragma.h
  - souffle/AstComponentChecker.h
  - souffle/WriteStreamCSV.h
  - souffle/AstTypeAnalysis.h
  - souffle/AstRelation.h
  - souffle/AstTransformer.h
  - souffle/SymbolTable.h
  - souffle/AstFunctorDeclaration.h
  - souffle/ComponentInstantiationTransformer.h
  - souffle/json11.h
  - souffle/AstProgram.h
  - souffle/ParserDriver.h
  - souffle/IOSystem.h
  - souffle/UnionFind.h
  - souffle/RamTransformer.h
  - souffle/IterUtils.h
  - souffle/ReadStreamSQLite.h
  - souffle/RamComplexityAnalysis.h
  - souffle/AstConstraintAnalysis.h
  - souffle/BTree.h
  - souffle/InterpreterGenerator.h
  - souffle/InterpreterNode.h
  - souffle/AstAnalysis.h
  - souffle/profile/htmlMain.h
  - souffle/profile/Reader.h
  - souffle/profile/Relation.h
  - souffle/profile/htmlJsChartistPlugin.h
  - souffle/profile/DataComparator.h
  - souffle/profile/Iteration.h
  - souffle/profile/htmlJsTableSort.h
  - souffle/profile/htmlJsUtil.h
  - souffle/profile/StringUtils.h
  - souffle/profile/Cell.h
  - souffle/profile/HtmlGenerator.h
  - souffle/profile/ProgramRun.h
  - souffle/profile/Cli.h
  - souffle/profile/CellInterface.h
  - souffle/profile/htmlCssStyle.h
  - souffle/profile/Tui.h
  - souffle/profile/htmlCssChartist.h
  - souffle/profile/Rule.h
  - souffle/profile/Table.h
  - souffle/profile/OutputProcessor.h
  - souffle/profile/UserInputReader.h
  - souffle/profile/htmlJsMain.h
  - souffle/profile/Row.h
  - souffle/profile/htmlJsChartistMin.h
  - souffle/ProfileDatabase.h
  - souffle/RamExpression.h
  - souffle/RamProgram.h
  - souffle/AstPragmaChecker.h
  - souffle/AstUtils.h
  - souffle/gzfstream.h
  - souffle/RamNode.h
  - souffle/InterpreterProgInterface.h
  - souffle/SerialisationStream.h
  - souffle/AstTranslationUnit.h
  - souffle/CompiledSouffle.h
  - souffle/PrecedenceGraph.h
  - souffle/ExplainProvenance.h
  - souffle/AuxArityAnalysis.h
  - souffle/RamRelation.h
  - souffle/AstSemanticChecker.h
  - souffle/AggregateOp.h
  - souffle/ProfileEvent.h
  - souffle/Table.h
  - souffle/ErrorReport.h
  - souffle/WriteStream.h
  - souffle/Synthesiser.h
  - souffle/RamTransforms.h
  - souffle/SignalHandler.h
  - souffle/RamTypes.h
  - souffle/ReadStream.h
  - souffle/Logger.h
  - souffle/PiggyList.h
  - souffle/InterpreterContext.h
  - souffle/RelationTag.h
  - souffle/TypeSystem.h
  - souffle/RamUtils.h
  - souffle/SouffleInterface.h
  - souffle/BinaryConstraintOps.h
  - souffle/RamOperation.h
  - souffle/DebugReport.h
  - souffle/CompiledTuple.h
  - souffle/InterpreterRelation.h
  - souffle/EquivalenceRelation.h
  - souffle/LogStatement.h
  - souffle/AstTypeEnvironmentAnalysis.h
  - souffle/utility/tinyformat.h
  - souffle/utility/FileUtil.h
  - souffle/utility/ParallelUtil.h
  - souffle/utility/StringUtil.h
  - souffle/utility/CacheUtil.h
  - souffle/utility/ContainerUtil.h
  - souffle/utility/MiscUtil.h
  - souffle/utility/EvaluatorUtil.h
  - souffle/utility/FunctionalUtil.h
  - souffle/utility/StreamUtil.h
  - souffle/CompiledOptions.h
  - souffle/GraphUtils.h

library:
  source-dirs:        lib
  cxx-sources:        cbits/*.cpp
  cxx-options:
    - -Wall
  when:
    - condition: os(linux)
      extra-libraries: stdc++
  generated-other-modules:
    - Paths_souffle_haskell

tests:
  souffle-haskell-test:
    main:             test.hs
    source-dirs:      tests
    cxx-sources:      tests/fixtures/*.cpp
    when:
      - condition: os(darwin)
        extra-libraries: c++
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - souffle-haskell
    cxx-options:
      - -D__EMBEDDED_SOUFFLE__
