name:                souffle-haskell
synopsis:            Souffle Datalog bindings for Haskell
description:         Souffle Datalog bindings for Haskell.
version:             0.2.3
homepage:            https://github.com/luc-tielen/souffle-haskell#README.md
license:             MIT
author:              Luc Tielen
maintainer:          luc.tielen@gmail.com
copyright:           2020 Luc Tielen
category:            Logic Programming, Foreign Binding, Bindings
github:              luc-tielen/souffle-haskell
extra-source-files:
  - README.md
  - CHANGELOG.md
  - LICENSE
  - cbits/**/*.h
  - cbits/souffle/LICENSE

dependencies:
  - base >= 4.12 && < 5
  - mtl >= 2.0 && < 3
  - template-haskell >= 2 && < 3
  - type-errors-pretty >= 0.0.1.0 && < 1
  - text >= 1.0 && < 2
  - vector <= 1.0
  - deepseq >= 1.4.4 && < 2
  - directory >= 1.3.3 && < 2
  - filepath  >= 1.4.2 && < 2
  - temporary >= 1.3 && < 2
  - process >= 1.6 && < 2

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -Weverything
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-implicit-prelude
  - -Wno-missed-specializations
  - -Wno-all-missed-specializations
  - -Wno-missing-import-lists
  - -Wno-type-defaults
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-missing-deriving-strategies
  - -optP-Wno-nonportable-include-path
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

cxx-options:
  - -std=c++17

include-dirs:
  - cbits
  - cbits/souffle

install-includes:
  - RamTypes.h
  - utility/MiscUtil.h
  - SymbolTable.h
  - json11.h
  - utility/FunctionalUtil.h
  - utility/StreamUtil.h
  - utility/StringUtil.h
  - ReadStreamCSV.h
  - ReadStream.h
  - utility/ContainerUtil.h
  - utility/FileUtil.h
  - gzfstream.h
  - CompiledTuple.h
  - RecordTable.h
  - Brie.h
  - utility/CacheUtil.h
  - SouffleInterface.h
  - EventProcessor.h
  - ProfileDatabase.h
  - WriteStreamSQLite.h
  - WriteStream.h
  - utility/ParallelUtil.h
  - LambdaBTree.h
  - BTree.h
  - WriteStreamCSV.h
  - utility/tinyformat.h
  - IOSystem.h
  - ReadStreamSQLite.h
  - UnionFind.h
  - PiggyList.h
  - ProfileEvent.h
  - profile/DataComparator.h
  - profile/CellInterface.h
  - profile/Row.h
  - profile/Table.h
  - SerialisationStream.h
  - CompiledSouffle.h
  - EquivalenceRelation.h
  - IterUtils.h
  - SignalHandler.h
  - utility/EvaluatorUtil.h
  - CompiledOptions.h
  - Logger.h

library:
  source-dirs:        lib
  cxx-sources:        cbits/*.cpp
  cxx-options:
    - -Wall
  when:
    - condition: os(linux)
      extra-libraries: stdc++
  generated-other-modules:
    - Paths_souffle_haskell

tests:
  souffle-haskell-test:
    main:             test.hs
    source-dirs:      tests
    cxx-sources:      tests/fixtures/*.cpp
    when:
      - condition: os(darwin)
        extra-libraries: c++
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - souffle-haskell
    cxx-options:
      - -D__EMBEDDED_SOUFFLE__

# NOTE: only used when having to update the souffle C headers
executables:
  import-souffle-headers:
    main:             import_souffle_headers.hs
    source-dirs:      scripts
    dependencies:
      - souffle-haskell
      - megaparsec >= 7.0.5 && < 8
      - containers >= 0.6.2.1 && < 1
