name:                souffle
version:             0.0.1
homepage:            https://github.com/luc-tielen/souffle-haskell#README.md
license:             MIT
author:              Luc Tielen
maintainer:          luc.tielen@gmail.com
copyright:           2019 Luc Tielen
category:            Web
extra-source-files:
- README.md
- LICENSE

custom-setup:
  dependencies:
    - base
    - directory
    - Cabal

dependencies:
  - base >= 4.11.0 && < 5
  - template-haskell >= 2.15 && < 3

default-extensions:
  - OverloadedStrings

cpp-options:
  - -D__EMBEDDED_SOUFFLE__

ghc-options:
  - -Wall
  - -Weverything
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-implicit-prelude
  - -Wno-missed-specializations
  - -Wno-all-missed-specializations
  - -Wno-missing-import-lists
  - -Wno-type-defaults
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-missing-deriving-strategies
  - -optP-Wno-nonportable-include-path
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

library:
  source-dirs:        lib
  cxx-sources:        cbits/*.cpp
  cxx-options:
    - -Wall
    - -O0

# TODO remove
executables:
  souffle-exe:
    source-dirs:      src
    main:             Main.hs
    extra-libraries:    c++
    dependencies:
      - souffle

tests:
  souffle-test:
    main:             test.hs
    source-dirs:      tests
    dependencies:
      - hspec >= 2.6.1 && < 3.0.0
      - neat-interpolation >= 0.3.2.4 && < 1
      - souffle

